### ISSUE TITLE
Add type hints

### ISSUE THREAD

**Issue by zupo** [niteoweb/pyramid_heroku#11]
What the title says. They must be checked on Travis on every run. 

Bonus karma points to calculate types coverage and fail Travis if under a certain number. We have this in woocart-app already: https://github.com/niteoweb/woocart-app/blob/master/Makefile#L80

**Comment by mandarvaze** [comment]
Link throws 404
I could not find "woocart-app" in the list of repos either.

If it is a private repo - this issue needs to be removed from "otasks"

**Comment by zupo** [comment]
I've open-sourced the script since then, your can find it at:
* https://github.com/Pylons/pyramid_openapi3/blob/master/Makefile#L35
* https://github.com/Pylons/pyramid_openapi3/blob/master/.mypy/type_coverage.py

**Comment by mandarvaze** [comment]
OK, I'll take a look at this.

**Comment by mandarvaze** [comment]
Here are the updates so far :

1. I "borrowed" `type_coverage.py` script from the above link
2. There is no `setup.cfg` here (like pyramind_openapi3) - so I used `--linecount-report typecov` option to run `mypy`
3. I made a trivial change to `pyramid_heroku/migrate.py` without which `mypy` won't even continue.
4. I was able to run the `type_coverage.py` (It failed due to just 15% coverage)
5. Looking at `.travis.yml`, I think if I add a line at the end, it should be sufficient. 

@zupo 

1. Is it OK to **copy** the `type_coverage.py` ? Linking just a single file from another git repo is non-trivial.
2. Should I also "copy" `setup.cfg` from `pyramid_openapi3`? Or is it OK to begin with command line option `--linecount-report typecov` ? (We can bring in `setup.cfg` later)
3. Do I need to run travis locally before I submit a PR ?

**Comment by zupo** [comment]
> Is it OK to copy the type_coverage.py?

Yes.

> Or is it OK to begin with command line option --linecount-report typecov?

Yes.

> Do I need to run travis locally before I submit a PR ?

No.

**Comment by mandarvaze** [comment]
@zupo I may have misunderstood the scope of this issue.

Is making type coverage 100% part of the scope of this issue ? 
Or 
just getting the infrastructure in place for checking the type coverage ?

Currently, the coverage is at 15%

I could change the min_coverage to 15, so that travis run passes for **this** PR.
Making the type_coverage 100% could be a separate task.

**Comment by zupo** [comment]
> ... fail Travis if under a certain number.

15 is good. And yes, getting coverage up to 100% is definitely a separate PR.

**Comment by mandarvaze** [comment]
Please see PR #28 (Finally travis passed)

**Comment by mandarvaze** [comment]
@zupo Now that the PR is merged, should this issue be closed ?
